# Generated by Django 4.2.11 on 2024-05-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newDivanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type_salary',
            field=models.CharField(choices=[('fixed', 'Фиксированный'), ('not_fixed', 'Сдельный')], max_length=50, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='pickupdelivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupdelivery_set', to='newDivanApp.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='technicalspecification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specifications', to='newDivanApp.order', verbose_name='Заказ'),
        ),
    ]
