# Generated by Django 4.2.11 on 2024-05-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newDivanApp', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
